### ISSUE TITLE
RES: Loja 1222 - Divergencia de preços na etiqueta - CBDQA323230

### ISSUE THREAD

**Issue by hugonn** [Tlantic/support#158]
"Pessoal podem me ajudar com o caso abaixo, o MRS está emitindo uma etiqueta com um valor diferente, pelo que entendi é um produto família, que o PLU tem mais de um EAN associado. Na base do MRS está correto o preço mas a etiqueta esta emitindo o valor “unitário” do produto tanto que na descrição demonstra 25g. Acontece somente com esse produto."

**Comment by hugonn** [comment]
Um email foi mandado questionando o cliente sobre o preço no POS porque, ao que parece, está divergindo com o preço da base do MRS

**Comment by leohickstein** [comment]
Situação resolvida.
