### ISSUE TITLE
Solicitação kit Implantação

### ISSUE THREAD

**Issue by leohickstein** [Tlantic/support#186]
Boa tarde,

Solicito a configuração e envio de 1 Kit de Implantação para o SuperPão.

O Kit deverá ser enviado para o escritório de SP.

Obrigada!

Att,
 
 
Regina Rangel
Project Manager
reginar@tlantic.com.br
Skype: reginatlantic
Work: +55 51 3320-1620

**Comment by eduardoclave** [comment]
Kit foi preparado e entregue na sexta-feira, 12/02/2016.
