### ISSUE TITLE
Solicitação Nota Fiscal de Transporte Kit Implantação

### ISSUE THREAD

**Issue by leohickstein** [Tlantic/support#187]
Aguardando retorno do financeiro, cfm email:

Viviane,

Solicito uma Nota Fiscal de Transporte para o nosso escritório de São Paulo (posteriormente será levado para o SuperPão) para os seguintes equipamentos:

Quantidade	Nº de Série	Descrição	NCM	CST	CFOP	Valor Unitário	Alíq. ICMS	Alíq. IPI
1	SW15KWF013583	IMPRESSORA PORTÁTIL LK-P12 INTERFACE	84433299	100	6.912	R$           2.800,00 	4	15
2	1525710440 / 1525710394	TERM. PORTATIL PM-260-LASER/BT/WI-	84719019	100	6.912	R$           2.400,00	4 	15 

OBS: Dados de NCM, CST, CFOP  e alíquotas coletados da Nota Fiscal que recebemos da Compex. Não esquecer de constar na NF os números de série dos equipamentos. TEMOS URGÊNCIA NA EMISSÃO DESSA NF DE TRANSPORTE!

Att,
 
 

	Eduardo Clavé da Silveira
Analista de Infraestrutura
Technology
email: eduardoc@tlantic.com.br
work: +55 51 3320-1700
Skype: eduardo.clave

**Comment by eduardoclave** [comment]
NF recebida de Viviane na sexta-feira, 12/02/2016.
