### ISSUE TITLE
Confirmar quais lojas ativas Telemaco

### ISSUE THREAD

**Issue by leohickstein** [Tlantic/support#205]

**Comment by eduardoclave** [comment]
Ok, confirmei a quantidade/tipo/modelo dos equipamentos que está com clientes SaaS:

MonteSerrat
Tipo	Fabricante	Modelo	Quantidade
Coletor	DataLogic	Skorpio X3	9
Impressora	Zebra	QL220	2
Impressora	Sewoo	LK-P41B	1

SuperPão
Tipo	Fabricante	Modelo	Quantidade
Coletor	HoneyWell	6500LB	1
Coletor	Point Mobile	PM260	4
Impressora	Sewoo	LK-P12	2

Telêmaco
Tipo	Fabricante	Modelo	Quantidade
Coletor	DataLogic	Skorpio X3	2
Impressora	Zebra	QL220	2

Essas informações foram registradas no OneNote do Suporte.
