### ISSUE TITLE
I15-135346 - Lentidão no Preenchimento do Simulador

### ISSUE THREAD

**Issue by rgomes-TLANTIC** [Tlantic/support#25]

**Comment by leohickstein** [comment]
Esta situação deverá virar um PM e ficar aos cuidados da Elisabete Freitas. Para isso ela solicitou diversas informações que já foram respondidas.
No momento estamos no aguardo dela encaminhar este assunto junto ao Joel Braga.

**Comment by leohickstein** [comment]
Elisabete delegou ao Hugo Couto a criação do PM. Ele chegou a me ligar para alinhar e já fechou o registro e abriu o PM. O PM deverá ficar com eles para ser endereçado junto ao GA do powersheets Ricardo Castro.
