### ISSUE TITLE
I15-135325 - Funcionalidade Import Article Information from Excel

### ISSUE THREAD

**Issue by rgomes-TLANTIC** [Tlantic/support#26]

**Comment by rgomes-TLANTIC** [comment]
Aguardando por fecho de projeto "Melhorias" e "500 linhas" e homologação em suporte para seguir na implementação da solução.

**Comment by leohickstein** [comment]
Já temos implementação para disponibilizarmos a Sofia, entretanto nas férias do Rafa estou sem acesso a folder para realização das passagens. Já efetuei o pedido para o Ricardo Castro.
