### ISSUE TITLE
#29 Visualizar os itens que foram marcados como não encontrados

### ISSUE THREAD

**Issue by leohickstein** [Tlantic/support#261]
O cliente sente a necessidade de poder verificar os produtos que foram "indicados" como não localizados durante a realização das tarefas de Remarcação e Auditorias.

Internal Issue: 
Found In: 4.1.4.9
Released: 
Related Issue: Tlantic/instore#1009 and Tlantic/instore#955

**Comment by leohickstein** [comment]
Edu, por favor valide se na versão atualmente em produção este problema já está resolvido.

**Comment by eduardoclave** [comment]
Ok, validado. Seguem abaixo as evidências dessa validação.

![20160225_131438](https://cloud.githubusercontent.com/assets/7000582/13326148/78fa4638-dbc3-11e5-9419-402998159d5d.jpg)
![20160225_131520](https://cloud.githubusercontent.com/assets/7000582/13326158/7d689184-dbc3-11e5-8f82-35de3c83ce59.jpg)
