### ISSUE TITLE
I15-451338 - Impossibilidade de aceder a zonas de contagem no PDA

### ISSUE THREAD

**Issue by leohickstein** [Tlantic/support#3]

**Comment by leohickstein** [comment]
Aguardando utilizador, primeiro comentário em 29/06.

**Comment by leohickstein** [comment]
Aguardando utilizador, segundo comentário em 30/06.

**Comment by tiagolvsantos** [comment]
Resolvido por falta de informação

**Comment by tiagolvsantos** [comment]
Re-Aberto novo input do user. 
- Falha de comunicação com o servidor

**Comment by tiagolvsantos** [comment]
A espera do numero de artigos por inventário

**Comment by tiagolvsantos** [comment]
Abertura das Zonas em Retek e encerramento das mesmas através do backOffice do MRS
