### ISSUE TITLE
Ajuste Build novo PDA PM260 - 16/dez

### ISSUE THREAD

**Issue by jonathanvoloski** [Tlantic/support#73]
ajustar build para Saas

**Comment by jonathanvoloski** [comment]
dependência de instalação do pacote de services no nosso ambiente

**Comment by hugonn** [comment]
Devido a muitos problemas encontrados para debugar o PDA e as formações agendadas para sexta, foi necessário remanejar a data de entrega para dia 14/dez

**Comment by hugonn** [comment]
Algumas divergências entre versões estão impossibilitando a ação deste ajuste. Esperando  merge entre versões de Produto e SAAS
